### ISSUE TITLE
Step-by-step tutorials to get students startet 

### ISSUE THREAD

**Issue by ceedee666** [ceedee666/cloud_based_is#1]
@MartinPankraz can we link to some step-by-step tutorials in the section [Getting Started](https://github.com/ceedee666/cloud_based_is#getting-started) section? I would hope we could find something like that:

1. Steps to sign up (if necessary, maybe easy enough). At least the link to where to create the first account.
2. Build the first "thing" using the new account. MAybe we can select a particular learning path or a few learning paths every student should work through.

**Comment by ceedee666** [comment]
Maybe one of the following?

- [PL-900: Microsoft Power Platform Fundamentals](https://docs.microsoft.com/en-us/learn/paths/power-plat-fundamentals/)
- [Automate a business process using Power Automate](https://docs.microsoft.com/en-us/learn/paths/automate-process-power-automate/)

But I'm simply guessing here... No idea if they fit.

**Comment by MartinPankraz** [comment]
Yes, we can become more concrete in the line-up.

1. The links listed in "Getting Started" are self-explanatory to create you first account. However we can adjust the wording to be more explicit why they are listed there.
2. Your link suggestions would work in terms of foundation. the second bullet point would be close to the skills needed for the excercise and PL-900 lays overall foundation. The scope of PL900 would be a little beyond our goals though.

How about we give suggestions and let the students explore themselves? [https://docs.microsoft.com/en-us/learn/browse](https://docs.microsoft.com/en-us/learn/browse).

How about we add these to spark the right level of curiosity to foster self-research?

[https://docs.microsoft.com/en-us/learn/modules/ai-machine-learning-fundamentals/](https://docs.microsoft.com/en-us/learn/modules/ai-machine-learning-fundamentals/)
[https://docs.microsoft.com/en-us/learn/paths/build-custom-text-analytics/](https://docs.microsoft.com/en-us/learn/paths/build-custom-text-analytics/)
[https://docs.microsoft.com/en-us/learn/paths/process-translate-text-azure-cognitive-services/](https://docs.microsoft.com/en-us/learn/paths/process-translate-text-azure-cognitive-services/)

@hobru what do you think?
